# Generated by Django 3.2 on 2021-09-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zayavka',
            name='total',
            field=models.CharField(blank=True, max_length=99999999, null=True, verbose_name='Сумма'),
        ),
    ]
