# Generated by Django 3.2 on 2021-09-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_zayavka_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavka',
            name='house',
            field=models.IntegerField(choices=[(200, 'Дом'), (100, 'Квартира'), (300, 'Офис')], verbose_name='Выберите помещение'),
        ),
    ]
