# Generated by Django 3.2 on 2021-09-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210905_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='zayavka',
            name='phone',
            field=models.CharField(default=1, max_length=11, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
