# Generated by Django 3.2 on 2021-09-10 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210910_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavka',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.place', verbose_name='Выберите помещение'),
        ),
    ]
