# Generated by Django 3.2 on 2021-09-13 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_zayavka_house'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Помещение', 'verbose_name_plural': 'Помещения'},
        ),
    ]
