# Generated by Django 3.2 on 2021-09-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_place_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True, verbose_name='Ссылка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usluga',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True, verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
