# Generated by Django 3.2 on 2021-09-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210915_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usluga',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Ссылка'),
        ),
    ]
