# Generated by Django 3.2 on 2021-09-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_usluga_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavka',
            name='statuc',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'В ожидании'), (2, 'На отработке'), (3, 'Заказ выполнен')], default=1, null=True, verbose_name='Статус заявки'),
        ),
    ]
