# Generated by Django 3.2 on 2021-09-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_zayavka_statuc'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='in_work',
            field=models.BooleanField(default=False, verbose_name='Занятость'),
        ),
    ]
