# Generated by Django 3.2 on 2021-09-17 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_zayavka_statuc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='usluga',
            name='slug',
        ),
    ]
