# Generated by Django 3.2 on 2021-09-17 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavka',
            name='house',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.place', verbose_name='Выберите помещение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='usluga',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.usluga', verbose_name='Услуга'),
            preserve_default=False,
        ),
    ]
