# Generated by Django 3.2 on 2021-09-17 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210917_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavka',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.place', verbose_name='Выберите помещение'),
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='usluga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.usluga', verbose_name='Услуга'),
        ),
    ]
