# Generated by Django 3.2 on 2021-09-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210917_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavka',
            name='metr',
            field=models.IntegerField(blank=True, null=True, verbose_name='Площадь дома(м²)'),
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Номер телефона'),
        ),
    ]
