# Generated by Django 3.2 on 2021-09-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_zayavka_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavka',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
